from google import genai
import os

def generate_answer(question: str) -> str:
    """
    Generate an answer to a question using the Google Gemini API.

    :param question: The user's input question
    :return: The answer generated by the Gemini model
    """
    # The client gets the API key from the environment variable `GEMINI_API_KEY`.
    client = genai.Client()
    
    response = client.models.generate_content(
        model="gemini-1.5-flash", 
        contents=question
    )
    return response.text.strip()

def answer_to_script(answer: str, question: str) -> str:
    """
    Convert the detailed answer into a conversational script suitable for a video presentation.
    The length of the script will be controlled to be between approximately 30 seconds and 1 minute.

    :param answer: The original answer generated by the LLM
    :param question: The user's original input question
    :return: The converted conversational script
    """
    # The client gets the API key from the environment variable `GEMINI_API_KEY`.
    client = genai.Client()

    # Modified prompt to strictly request only the script output.
    prompt = f"""
    Your task is to convert the following text into a conversational script for a video presentation.
    The script should be between 30 seconds and 1 minute long.
    Use simple, easy-to-understand language and avoid technical jargon.
    Your output MUST be only the script text itself, without any additional explanations, titles, or formatting like "Scenario Description:" or "Script:".

    Original Question:
    {question}

    Original Answer:
    {answer}
    """
    
    response = client.models.generate_content(
        model="gemini-1.5-flash",
        contents=prompt
    )
    return response.text.strip()

if __name__ == "__main__":
    # Ensure your GEMINI_API_KEY is set as an environment variable before running.
    if "GEMINI_API_KEY" not in os.environ:
        print("Please set the GEMINI_API_KEY environment variable.")
    else:
        # Test script generator
        print("--- Step 1: Generate Answer ---")
        question = "What is a quantum computer?\nAnd how is it different from a classical computer?"
        
        try:
            raw_answer = generate_answer(question)
            print(f"Original question: {question}")
            print("-" * 20)
            print("LLM Original Answer:")
            print(raw_answer)

            print("\n--- Step 2: Convert to Script ---")
            script = answer_to_script(raw_answer, question)
            print("-" * 20)
            print("Converted Script:")
            print(script)

        except Exception as e:
            print(f"An error occurred: {e}")