import google.generativeai as genai

def generate_answer(question: str) -> str:
    """
    Generate an answer to a question using the Google Gemini API.

    :param question: The user's input question
    :return: The answer generated by the Gemini model
    """
    model = genai.GenerativeModel('gemini-1.5-flash')
    response = model.generate_content(question)
    return response.text.strip()

def answer_to_script(answer: str, question: str) -> str:
    """
    Convert the detailed answer into a conversational script suitable for a video presentation.
    The length of the script will be controlled to be between approximately 30 seconds and 1 minute.

    :param answer: The original answer generated by the LLM
    :param question: The user's original input question
    :return: The converted conversational script
    """
    model = genai.GenerativeModel('gemini-1.5-flash')

    # Design a prompt to convert the LLM's answer into a conversational and presentation-friendly script.
    prompt = f"""
    Please convert the following answer about the question below into a conversational script suitable for a video presentation, with a length of about 30 seconds to 1 minute.
    Please use simple and easy-to-understand vocabulary, avoid excessive technical jargon, so that even a non-technical audience can understand.
    
    Question:
    {question}

    Original answer:
    {answer}
    """
    
    response = model.generate_content(prompt)
    return response.text.strip()

if __name__ == "__main__":
    # Test script generator
    print("--- Step 1: Generate Answer ---")
    question = "What is a quantum computer?\nAnd how is it different from a classical computer?"
    
    try:
        raw_answer = generate_answer(question)
        print(f"Original question: {question}")
        print("-" * 20)
        print("LLM Original Answer:")
        print(raw_answer)

        print("\n--- Step 2: Convert to Script ---")
        script = answer_to_script(raw_answer, question)
        print("-" * 20)
        print("Converted Script:")
        print(script)

    except Exception as e:
        print(f"An error occurred: {e}")
        print("Please check if your GEMINI_API_KEY is set correctly.")
        print(script)

    except Exception as e:
        print(f"An error occurred: {e}")
        print("Please check if your GEMINI_API_KEY is set correctly.")
